src/Entity/Prof.php
<?php

namespace App\Entity;

use App\Repository\ProfRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProfRepository::class)]
class Prof
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_prof = null;

    #[ORM\ManyToMany(targetEntity: Classe::class)]
    private Collection $classe;

    #[ORM\ManyToMany(targetEntity: Matiere::class)]
    private Collection $matiere;

    public function __construct()
    {
        $this->classe = new ArrayCollection();
        $this->matiere = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProf(): ?string
    {
        return $this->nom_prof;
    }

    public function setNomProf(string $nom_prof): static
    {
        $this->nom_prof = $nom_prof;

        return $this;
    }

    /**
     * @return Collection<int, Classe>
     */
    public function getClasse(): Collection
    {
        return $this->classe;
    }

    public function addClasse(Classe $classe): static
    {
        if (!$this->classe->contains($classe)) {
            $this->classe->add($classe);
        }

        return $this;
    }

    public function removeClasse(Classe $classe): static
    {
        $this->classe->removeElement($classe);

        return $this;
    }

    /**
     * @return Collection<int, Matiere>
     */
    public function getMatiere(): Collection
    {
        return $this->matiere;
    }

    public function addMatiere(Matiere $matiere): static
    {
        if (!$this->matiere->contains($matiere)) {
            $this->matiere->add($matiere);
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): static
    {
        $this->matiere->removeElement($matiere);

        return $this;
    }
}

src/Controller/ProfController.php
<?php

namespace App\Controller;

use App\Entity\Prof;
use App\Form\ProfType;
use App\Repository\ProfRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfController extends AbstractController
{
    #[Route('/prof', name: 'app_prof')]
    public function index(ProfRepository $profRepository): Response
    {
        $profs = $profRepository->findBy([], ['nom_prof' => 'ASC']);

        return $this->render('prof/index.html.twig', [
            'profs' => $profs,
        ]);
    }

    #[Route('/prof/create', name: 'app_prof_create')]
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $prof = new Prof();
        $form = $this->createForm(ProfType::class, $prof);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($prof);
            $entityManager->flush();

            return $this->redirectToRoute('app_prof');
        }

        return $this->render('prof/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/prof/edit/{id}', name: 'app_prof_edit')]
    public function edit(Request $request, Prof $prof, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProfType::class, $prof);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_prof');
        }

        return $this->render('prof/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/prof/delete/{id}', name: 'app_prof_delete')]
    public function delete(Request $request, Prof $prof, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($prof);
        $entityManager->flush();

        return $this->redirectToRoute('app_prof');
    }
}

templates/prof/create.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('Assets/CSS/styles.css') }}" />

    <title>Création d'un professeur</title>
</head>
<body>
    {% include 'header.html.twig' %}
  
    <div class="container">
        <h1>Création d'un professeur</h1>

        {{ form_start(form) }}
        {{ form_row(form.nom_prof) }} 
        {{ form_row(form.classe) }} 
        {{ form_row(form.matiere) }} 

        <button type="submit" class="button">Créer</button>
        <a href="{{ path('app_prof') }}" class="button">Retour</a>

        {{ form_end(form) }}
    </div>


</body>
</html>

templates/prof/edit.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('Assets/CSS/styles.css') }}" />

    <title>Modification du professeur</title>
</head>
<body>
    {% include 'header.html.twig' %}
  
    <div class="container">
        <h1>Modification du professeur</h1>

        {{ form_start(form) }}
        {{ form_row(form.nom_prof) }}
        {{ form_row(form.classe) }}
        {{ form_row(form.matiere) }}

        <button type="submit" class="button">Modifier</button>
        <a href="{{ path('app_prof') }}" class="button">Retour</a>

        {{ form_end(form) }}
    </div>


</body>
</html>

templates/prof/index.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('Assets/CSS/styles.css') }}" />

    <title>Liste des professeurs</title>
</head>
<body>
    {% include 'header.html.twig' %}
  
   <div class="container">
        <h1>Liste des professeurs</h1>
        <a href="{{ path('app_prof_create') }}" class="button">Créer un professeur</a>


        <table class="table">
            <thead>
                <tr>
                    {# <th>ID</th> #}
                    <th>Nom</th>
                    <th>Classes</th>
                    <th>Matieres</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for prof in profs %}
                    <tr>
                        {# <td>{{ prof.id }}</td> #}
                        <td>{{ prof.nomProf }}</td>
                        <td>
                            {% for classe in prof.classe %}
                                {{ classe.nom }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for matiere in prof.matiere %}
                                {{ matiere.nom }}{% if not loop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            <a href="{{ path('app_prof_edit', {id: prof.id}) }}" class="button">Modifier</a>
                            <a href="{{ path('app_prof_delete', {id: prof.id}) }}" class="button" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce professeur ?')">Supprimer</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

      
    </div>


</body>
</html>